In [ ]:
import numpy as np
a = np.array([1,2,3])
print(type(a))

<class 'numpy.ndarray'>


In [ ]:
a[0]

1

In [ ]:
b = np.array(['A','B','C'])
b

array(['A', 'B', 'C'], dtype='<U1')

In [ ]:
import numpy as np
ratul = np.array([1,2,3,4],np.int64)



In [ ]:
ratul[0]

1

In [ ]:
import numpy as np
ratul = np.array([[1,2,3,4]],np.int64)



In [ ]:
ratul[0,1]

2

In [ ]:
ratul.shape

(1, 4)

In [ ]:
ratul.dtype

dtype('int64')

# M1 Array creation from python Structure

In [ ]:
threedimesionalarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
threedimesionalarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
threedimesionalarray[1,0]

4

In [ ]:
threedimesionalarray.shape

(3, 3)

In [ ]:
threedimesionalarray.size

9

In [ ]:
np.array([2,3,4])

array([2, 3, 4])

In [ ]:
np.array({2,3,4})

array({2, 3, 4}, dtype=object)

# M2 Intrinsic Numpy array creation Object  

In [ ]:
a = np.zeros((2,3))

In [ ]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a = np.linspace(1,50,10)
a

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [ ]:
emp = np.empty((4,6))
emp

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [ ]:
arr = np.arange(99)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr = arr.reshape(3,33)


In [ ]:
arr.shape

(3, 33)

In [ ]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [ ]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.shape

(3, 33)

In [17]:
a = [[1,2,3],[4,5,6],[7,8,9]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:

import numpy as np
a= np.array(a)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
a.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [20]:
a.argmin()

0

In [23]:
a.argmax(axis = 1)

array([2, 2, 2])

In [3]:
a.sum(axis =0)

array([12, 15, 18])

In [4]:
a.sum(axis =1)

array([ 6, 15, 24])

In [5]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [6]:
a.flat

In [10]:
for item in a.flat:
  print(item.T)

1
2
3
4
5
6
7
8
9


finding out the maximum index value 1D

In [45]:
one = np.array([1,2,3,120,130,20])

In [47]:
one[1:4]

array([  2,   3, 120])

In [48]:
one[1:]

array([  2,   3, 120, 130,  20])

In [49]:
one[:-1]

array([  1,   2,   3, 120, 130])

In [53]:
one[::-2]

array([ 20, 120,   2])

In [52]:
one[::-3]

array([20,  3])

In [46]:
one.argmax()

4

In [15]:
one.argmin()

0

In [16]:
one.argsort()

array([0, 1, 2, 5, 3, 4])

In [64]:
one

array([  1,   2,   3, 120, 130,  20])

In [62]:
one>10

array([False, False, False,  True,  True,  True])

In [63]:
one[one>10]

array([120, 130,  20])

**2D**

In [65]:
a


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [66]:
a.shape

(3, 3)

In [68]:
a.reshape(2,4)

ValueError: cannot reshape array of size 9 into shape (2,4)

In [56]:
two = a
two[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [58]:
two[:,1]

array([2, 5, 8])

In [60]:
two [1:,0:2]

array([[4, 5],
       [7, 8]])

In [26]:
b = a
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
c= b*a
c

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [28]:
np.sqrt(b)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [33]:
b[0,0]

1

In [39]:
c.max()

81

In [40]:
c.min()

1

In [44]:
c[1:]

array([[16, 25, 36],
       [49, 64, 81]])